<?php
// This file is the original viewer.html sample, with some changes:
// - css and script are set via Zend,
// - the file is set via a variable instead of a url anchor parameter,
// - a noscript element is added at the end,
// By this way, it can be overridden and customized via the theme, if needed.

?>
<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var string $style
 */

$translate = $this->plugin('translate');
echo $this->doctype();
echo $this->htmlElement('html')->setAttribute('lang', $this->lang());
echo $this->headMeta()->appendHttpEquiv('text/html; charset=utf-8');
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0');
?>
<!--
  Copyright (C) 2012-2015 KO GmbH <copyright@kogmbh.com>
  This file is part of ViewerJS.

  ViewerJS is free software: you can redistribute it and/or modify it
  under the terms of the GNU Affero General Public License (GNU AGPL)
  as published by the Free Software Foundation, either version 3 of
  the License, or (at your option) any later version.

  ViewerJS is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with ViewerJS.  If not, see <http://www.gnu.org/licenses/>.

  @source: http://viewerjs.org/
  @source: http://github.com/kogmbh/ViewerJS

  This file is a derivative from a part of Mozilla's PDF.js project. The
  original license header follows.

  Copyright 2012 Mozilla Foundation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

-->
<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/viewerjs/video-js.css', 'ViewerJs'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/viewerjs/viewer.css', 'ViewerJs'));
$this->headScript()->appendScript(
    'var basePath = ' . json_encode($this->basePath(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';
var documentUrl = ' . json_encode($media->originalUrl(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';'
);
$this->headScript()->appendFile($this->assetUrl('vendor/viewerjs/video.js', 'ViewerJs'));
$this->headScript()->appendFile($this->assetUrl('vendor/viewerjs/settings.js', 'ViewerJs'));
$this->headScript()->appendFile($this->assetUrl('vendor/viewerjs/viewer.js', 'ViewerJs'));
?>

<noscript>
  <p>
    <?php echo $this->escapeHtml($translate('This browser does not support PDF.')); ?>
    <?php echo sprintf($translate('You may %sdownload it%s to view it offline.'),
        '<a href="' . $media->originalUrl() . '">', '</a>'); ?>
    <img src="<?php echo $media->thumbnailUrl('large'); ?>" height="600px" />
  </p>
</noscript>

<script src="viewer.js" type="text/javascript" charset="utf-8"></script>
</body>
</html>
