<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

// No fallback for iframe in HTML5.

$escapeAttr = $this->plugin('escapeHtmlAttr');

$source = empty($options['source']) ? $resource->originalUrl() : $options['source'];
$url = $this->assetUrl('vendor/viewerjs/index.html', 'ViewerJs') . '&file=' . $source;
?>

<?php if (!empty($options['heading'])): ?>
    <h2><?= $options['heading'] ?></h2>
<?php endif; ?>

<iframe height="100%" width="100%" <?= $options['attributes'] ?>  src="<?= $escapeAttr($url) ?>"></iframe>
